config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#landing'

  get 'bikes', to: 'bikes#index', as: :bikes

  get 'bikes/map', to: 'bikes#index_map', as: :bikes_map

  get 'bikes/new', to: 'bikes#new', as: :new_bike

  get 'bikes/:id', to: 'bikes#show', as: :bike

  post 'bikes', to: 'bikes#create'

  get 'bikes/:id/edit', to: 'bikes#edit', as: :edit_bike

  patch 'bikes/:id', to: 'bikes#update'

  delete 'bikes/:id', to: 'bikes#destroy'

  get 'bookings', to: 'bookings#index', as: :bookings

  get 'rentals', to: 'bookings#rentals', as: :rentals
  # patch 'rentals/:id', to: 'bookings#update_rental'


  post 'bikes/:id/bookings', to: 'bookings#create', as: :bike_bookings

  patch 'bookings/:id/confirm', to: 'bookings#confirm', as: :booking_confirm
  patch 'bookings/:id/cancel', to: 'bookings#cancel', as: :booking_cancel

  delete 'bookings/:id', to: 'bookings#destroy', as: :booking_del

  get 'my-bikes', to: "bikes#index_owner", as: :my_bikes

  get 'users/:id/profile', to: "pages#profile", as: :user_profile

  get 'users/:id/profile/edit_profile_description', to: "pages#edit_profile_description", as: :edit_profile_description

  patch 'users/:id/profile', to: 'pages#update_profile'

  # Reviews paths
  post 'bikes/:bike_id/reviews', to: 'reviews#create', as: :bike_reviews
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :bike

  validates :start_date, :end_date, presence: true #, availability: true / commenting out for now since raising an error
  validates :confirmed, inclusion: { in: ['pending', 'confirmed', 'cancelled'] }
  validate :end_date_after_start_date

  private

  def end_date_after_start_date
    return if end_date.blank? || start_date.blank?

    if end_date < start_date
      errors.add(:end_date, "must be after the start date")
    end
 end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @current_user = current_user
    @bookings = Booking.where(user_id: @current_user).order("id")
  end

  def create
    @booking = Booking.new(review_params)
    @bike = Bike.find(params[:bike_id])
    @owner = User.find(@bike.user_id) # need this to pass it to the view when re-rendering render: 'bikes/show' below
    @booking.bike = @bike
    @booking.user = current_user
    authorize @booking
    if @booking.save
      @bike.dates[@booking.id] = [@booking.start_date, @booking.end_date]
      @bike.save
      redirect_to bike_path(@bike)
    else
      @bike__markers = {
        lat: @bike.latitude,
        lng: @bike.longitude,

        infoWindow: render_to_string(partial: "bikes/infowindow", locals: { bike: @bike })
      }
      render 'bikes/show'
    end
  end

  def confirm
    @booking = Booking.find(params[:id])
    authorize @booking
    @booking.confirmed = "confirmed"
    @booking.save
    redirect_to rentals_path
  end

  def cancel
    @booking = Booking.find(params[:id])
    authorize @booking
    @booking.confirmed = "cancelled"
    @booking.save
    if params["rentals"] == "true"
      redirect_to rentals_path
    else
      redirect_to bookings_path
    end
  end

  def rentals
    @bikes = Bike.where(user:current_user)
    @bookings = []
    @bikes.each do |bike|
      bike.bookings.each do |booking|
        @bookings << booking
      end
    end
    authorize Booking
  end

  def destroy
    @booking = Booking.find(params[:id])
    authorize @booking

    @booking.destroy

    redirect_to rentals_path
  end

  private

  def review_params
    params.require(:booking).permit(:start_date, :end_date, :bike_id)
  end
end

app/views/bookings/:index.html.erb
<h1>Bookings#:index</h1>
<p>Find me in app/views/bookings/:index.html.erb</p>

app/views/bookings/:rentals.html.erb
<h1>Bookings#:rentals</h1>
<p>Find me in app/views/bookings/:rentals.html.erb</p>

app/views/bookings/index.html.erb
<h1>My Bookings</h1>
<% if @destroy %>
  <div class="" role="">
    Bike successfully deleted
</div>
<% end %>
<div class="">
<% @bookings.each do |booking| %>
  <% booked_user = User.find(booking.user_id) %>
  <% booked_bike = Bike.find(booking.bike_id) %>
  <% owner_id = User.find(booked_bike.user_id) %>
  <div class="card-bookings my-3">
   <%= cl_image_tag booked_bike.photo %>
    <div class="card-bookings-infos d-flex flex-grow-1">
      <div class="flex-grow-1">
        <h2>Bike <%= booked_bike.name %></h2>

        <h5>Owned by: <%= owner_id.first_name%> <%=booked_user.last_name %></h5>
        <h6>FROM: <%= booking.start_date.strftime("%A, %b %d %Y") %></h6>
        <h6>TO  : <%= booking.end_date.strftime("%A, %b %d %Y") %></h6>
        <p><br></p>
        <h6><%= booking.confirmed.capitalize %></h6>

      </div>

      <div class="card-buttons-booked d-flex flex-column">
      <% case booking.confirmed %>
      <% when "pending" %>
        <%= link_to 'Cancel', booking_cancel_path(booking,rentals: false), method: 'patch',class: "btn btn-danger btn-md btn-block my-2" %>
      <% when "confirmed" %>
        <%= link_to 'Cancel', booking_cancel_path(booking,rentals: false), method: 'patch',class: "btn btn-danger btn-md btn-block my-2" %>
      <% end %>

      </div>
    </div>
  </div>
<% end %>

app/views/bookings/rentals.html.erb
<h1>My Rentals</h1>
<% if @destroy %>
  <div class="" role="">
    Bike successfully deleted
</div>
<% end %>
<div class="">
<% @bookings.each do |booking| %>
  <% booked_user = User.find(booking.user_id) %>
  <% booked_bike = Bike.find(booking.bike_id) %>
  <div class="card-bookings my-3 bookings-page">
   <%= cl_image_tag booked_bike.photo %>
    <div class="card-bookings-infos d-flex flex-grow-1">
      <div class="flex-grow-1">
        <h2>My Bike <%= booked_bike.name %></h2>

        <h5>Renter :<%= booked_user.first_name%> <%=booked_user.last_name %></h5>
        <h6>FROM: <%= booking.start_date.strftime("%A, %b %d %Y") %></h6>
        <h6>TO  : <%= booking.end_date.strftime("%A, %b %d %Y") %></h6>
        <p><br></p>


        <% if booking.confirmed == "confirmed" %>
          <!-- <h6 class="bg-success" style="width: 100px;"><%= booking.confirmed.capitalize %></h6> -->
          <div class="btn btn-success" style="">Confirmed</div>
        <% else %>
          <div class="btn"><%= booking.confirmed.capitalize %></div>
        <% end %>
      </div>

      <div class="card-buttons-booked d-flex flex-column align-items-end">
      <% case booking.confirmed %>
      <% when "pending" %>
        <%= link_to 'Confirm', booking_confirm_path(booking, rentals: true), method: 'patch', class: "btn btn-primary btn-md btn-block my-2" %>
        <%= link_to 'Cancel', booking_cancel_path(booking, rentals: true), method: 'patch',class: "btn btn-danger btn-md btn-block my-2" %>
      <% when "confirmed" %>
        <%= link_to 'Cancel', booking_cancel_path(booking, rentals: true), method: 'patch',class: "btn btn-danger btn-md btn-block my-2" %>
      <% when "cancelled" %>
        <% # link_to "Delete", bike_path(bike), method: "delete", class: "btn btn-danger delete-btn" %>
        <%= link_to 'Delete', booking_del_path(booking, rentals: true), method: 'delete',class: "btn btn-danger btn-md btn-block my-2" %>
      <% end %>

      </div>
    </div>
  </div>
<% end %>