config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#landing'

  get 'bikes', to: 'bikes#index', as: :bikes

  get 'bikes/map', to: 'bikes#index_map', as: :bikes_map

  get 'bikes/new', to: 'bikes#new', as: :new_bike

  get 'bikes/:id', to: 'bikes#show', as: :bike

  post 'bikes', to: 'bikes#create'

  get 'bikes/:id/edit', to: 'bikes#edit', as: :edit_bike

  patch 'bikes/:id', to: 'bikes#update'

  delete 'bikes/:id', to: 'bikes#destroy'

  get 'bookings', to: 'bookings#index', as: :bookings

  get 'rentals', to: 'bookings#rentals', as: :rentals
  # patch 'rentals/:id', to: 'bookings#update_rental'


  post 'bikes/:id/bookings', to: 'bookings#create', as: :bike_bookings

  patch 'bookings/:id/confirm', to: 'bookings#confirm', as: :booking_confirm
  patch 'bookings/:id/cancel', to: 'bookings#cancel', as: :booking_cancel

  delete 'bookings/:id', to: 'bookings#destroy', as: :booking_del

  get 'my-bikes', to: "bikes#index_owner", as: :my_bikes

  get 'users/:id/profile', to: "pages#profile", as: :user_profile

  get 'users/:id/profile/edit_profile_description', to: "pages#edit_profile_description", as: :edit_profile_description

  patch 'users/:id/profile', to: 'pages#update_profile'

  # Reviews paths
  post 'bikes/:bike_id/reviews', to: 'reviews#create', as: :bike_reviews
end

app/views/shared/_booking_form.html.erb
<% if bike.user != current_user %>
  <div class="col-xs-6 col-xs-offset-3 form__wrapper" data-unavailable="<%= bike.unavailable_dates.to_json %>">
    <%= simple_form_for ([@bike, @booking]) do |f| %>
      <%= f.input :start_date, as: :date, html5: true, input_html:  { class: "custom__input" }, class: 'xy' %>
      <%= f.input :end_date, as: :date, html5: true, disabled: true, input_html:  { class: "custom__input" } %>
      <%= hidden_field_tag(:bike_id, @bike.id) %>
      <%= f.submit "Book this bike!", id: "booking__submit" %>
    <% end %>
  </div>
  <% else %>
    <p>Sorry, you can't book your own bike <i class="fas fa-sad-tear"></i></p>
    <span class="tip">(psttt, just don't put it up for rent if you want to ride it...)</span>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

<% if flash[:just_created] %>
  <div id="created-alert" style="display: none"><%= flash[:just_created] %></div>
<% end %>

<% if flash[:just_updated] %>
  <div id="created-alert" style="display: none"><%= flash[:just_updated] %></div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "/", class: "navbar-brand" do %>
    <%= image_tag "bicycle.svg" %>
    <span id="logo-text" class="ml-2">BikeEazy</span>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse justify-content-between flex-grow-1" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Browse", bikes_path, class: "nav-link" %>
      </li>
    </ul>
    <ul class="navbar-nav mr-0">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to current_user.first_name, "#", class: "nav-link disabled" %>
        </li>
        <li class="nav-item dropdown">
        <div class="avatar dropdown-toggle" id="navbarDropdown" data-toggle="dropdown" aria-haspopup=true, aria-expanded=false >
          <%= avatar_for(current_user)%>
        </div>

          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "My Profile", user_profile_path(current_user), class: "dropdown-item" %>
            <%= link_to "My Bikes", my_bikes_path, class: "dropdown-item" %>
            <%= link_to "My Bookings", bookings_path, class: "dropdown-item" %>
            <%= link_to "My Rentals", rentals_path, class: "dropdown-item" %>
            <%= link_to "Account Settings", edit_user_registration_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>