config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#landing'

  get 'bikes', to: 'bikes#index', as: :bikes

  get 'bikes/map', to: 'bikes#index_map', as: :bikes_map

  get 'bikes/new', to: 'bikes#new', as: :new_bike

  get 'bikes/:id', to: 'bikes#show', as: :bike

  post 'bikes', to: 'bikes#create'

  get 'bikes/:id/edit', to: 'bikes#edit', as: :edit_bike

  patch 'bikes/:id', to: 'bikes#update'

  delete 'bikes/:id', to: 'bikes#destroy'

  get 'bookings', to: 'bookings#index', as: :bookings

  get 'rentals', to: 'bookings#rentals', as: :rentals
  # patch 'rentals/:id', to: 'bookings#update_rental'


  post 'bikes/:id/bookings', to: 'bookings#create', as: :bike_bookings

  patch 'bookings/:id/confirm', to: 'bookings#confirm', as: :booking_confirm
  patch 'bookings/:id/cancel', to: 'bookings#cancel', as: :booking_cancel

  delete 'bookings/:id', to: 'bookings#destroy', as: :booking_del

  get 'my-bikes', to: "bikes#index_owner", as: :my_bikes

  get 'users/:id/profile', to: "pages#profile", as: :user_profile

  get 'users/:id/profile/edit_profile_description', to: "pages#edit_profile_description", as: :edit_profile_description

  patch 'users/:id/profile', to: 'pages#update_profile'

  # Reviews paths
  post 'bikes/:bike_id/reviews', to: 'reviews#create', as: :bike_reviews
end

app/views/pages/edit_profile_description.html.erb
<%= simple_form_for @user, url: user_profile_path(@user), method: 'patch'  do |form| %>
  <%= form.input :profile_description %>
  <%= form.submit "Update description", class: "btn btn-primary", id: "update-btn" %>
<% end %>

app/views/pages/landing.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1541625810516-44f1ce894bcd?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80);">
  <div class="container">
    <h1>Avec<strong> Bike Easy</strong> trouver un vélo c'est comme 123!</h1>
    <p>Faites un tour de Montréal a Vélo et visitez la plus ville du Canada.</p>
    <!-- # views/devise/menu/_login_items.html.erb -->
    <% if !user_signed_in? %>
      <li>
      <%= link_to('Register', new_user_registration_path, class: "btn btn-secondary btn-lg")  %>
      <%= link_to('Browse', bikes_path, class: "btn btn-secondary btn-lg") %>
      </li>
    <% end %>
  </div>
</div>

app/views/pages/profile.html.erb
<div class="profile__wrapper">

  <div class="profile__content">
    <%= avatar_for(@user) %>
      <!-- <%= cl_image_tag(@user.avatar, class: 'profile__pic') %> -->
    <p class="specs__title book-me"> Hi! I'm <%= @user.first_name %></p>
    <p class="spec__info"><%= @user.profile_description %></p>
    <% if @user == current_user %>
      <%= link_to "Edit description", edit_profile_description_path(@user), class: "btn btn-primary edit_profile__btn" %>
    <% end %>
     <% if @user != current_user %>
      <p class="contact"><span class="contact__title">
        <a href="mailto:<%= @user.email %>?Subject=Information about your bikes" target="_blank" class="mailto">Contact <%= @user.first_name %></a>
      </p>
    <% end %>
  </div>
  <div class="profile__info">
    <h4 class="specs__title book-me">Check-out my bikes!</h4>
    <% @user.bikes.each do |bike| %>
      <div class="card-product my-5">
        <%= cl_image_tag bike.photo %>
        <div class="card-product-infos d-flex flex-grow-1 flex-column justify-content-between align-items-start profile__button">
          <div class="info-text flex-grow-1 d-flex justify-content-between">
            <div class="flex-grow-1">
              <div class="info-header d-flex justify-content-between align-items-center">
                <p class="bike-title"><%= bike.name %></p>
                <p class="category mt-0">
                  <%= bike.category %>
                </p>
              </div>

              <div class="category-reviews d-flex justify-content-between align-items-center"">


                <p class="price-per-night"><%= format('%.2f', bike.price) %>$ per day</p>

                <p class="reviews">
                  <% bike.rating.times do %>
                    <i class="fas fa-star star-green"></i>
                  <% end %>
                  (<%= rand(100) %> reviews)
                </p>
              </div>
            </div>

          </div>

          <div class="card-buttons d-flex justify-content-between align-items-center">
            <div class="profile__btn">
              <%= link_to "More info", bike_path(bike), class: "btn btn-primary profile__btn" %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>