config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#landing'

  get 'bikes', to: 'bikes#index', as: :bikes

  get 'bikes/map', to: 'bikes#index_map', as: :bikes_map

  get 'bikes/new', to: 'bikes#new', as: :new_bike

  get 'bikes/:id', to: 'bikes#show', as: :bike

  post 'bikes', to: 'bikes#create'

  get 'bikes/:id/edit', to: 'bikes#edit', as: :edit_bike

  patch 'bikes/:id', to: 'bikes#update'

  delete 'bikes/:id', to: 'bikes#destroy'

  get 'bookings', to: 'bookings#index', as: :bookings

  get 'rentals', to: 'bookings#rentals', as: :rentals
  # patch 'rentals/:id', to: 'bookings#update_rental'


  post 'bikes/:id/bookings', to: 'bookings#create', as: :bike_bookings

  patch 'bookings/:id/confirm', to: 'bookings#confirm', as: :booking_confirm
  patch 'bookings/:id/cancel', to: 'bookings#cancel', as: :booking_cancel

  delete 'bookings/:id', to: 'bookings#destroy', as: :booking_del

  get 'my-bikes', to: "bikes#index_owner", as: :my_bikes

  get 'users/:id/profile', to: "pages#profile", as: :user_profile

  get 'users/:id/profile/edit_profile_description', to: "pages#edit_profile_description", as: :edit_profile_description

  patch 'users/:id/profile', to: 'pages#update_profile'

  # Reviews paths
  post 'bikes/:bike_id/reviews', to: 'reviews#create', as: :bike_reviews
end

app/models/bike.rb
class Bike < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :users, through: :bookings
  has_many :reviews, dependent: :destroy

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  mount_uploader :photo, PhotoUploader

  validates :name, :photo, :price, presence: true
  validates :rating, inclusion: { in: [1, 2, 3, 4, 5] }
  # validates :gender, inclusion: { in: ['M', 'F'] }
  # validates :size, inclusion: { in: ['sm', 'md', 'lg'] }
  validates :category, inclusion: { in: ['Mountain', 'BMX', 'Road', 'Fixi', 'Electric', 'City', 'Fatbike'] }

  def unavailable_dates
    bookings.pluck(:start_date, :end_date).map do |range|
      { from: range[0], to: range[1] }
    end
  end
end

app/controllers/bikes_controller.rb
class BikesController < ApplicationController
  before_action :set_bike, only: %i[show edit update destroy]
  skip_before_action :authenticate_user!, only: %i[index show index_map]

  def index
    @no_container = true
    if params[:category].present?
      @category = params[:category]
      @rating = params[:rating][0].to_i
      user_id = current_user ? current_user.id : 0

      if @category == "All"
        @bikes = Bike.where("rating >= :rating AND user_id <> :user_id", rating: @rating, user_id: user_id)
        @message = 'all'
      else
        sql_query = " \
          category = :category \
          AND rating >= :rating \
          AND user_id <> :user_id
        "
        @bikes = Bike.where(sql_query, category: @category, rating: @rating, user_id: user_id)

        @message = 'category'
      end

      # @message = "We found #{pluralize @bikes.count, "bike"} in \"#{category}\", with a rating of #{params[:rating]} and above"
    else
      @bikes = Bike.all

      @message = false
    end
  end

  def index_map
    @bikes = Bike.where.not(latitude: nil, longitude: nil)

    @markers = @bikes.map do |bike|
      {
        lat: bike.latitude,
        lng: bike.longitude,
        infoWindow: render_to_string(partial: "infowindow", locals: { bike: bike })
      }
    end
  end

  def show
    @booking = Booking.new
    authorize @bike
    @bike__markers = {
      lat: @bike.latitude,
      lng: @bike.longitude,

      infoWindow: render_to_string(partial: "infowindow", locals: { bike: @bike })
    }
    @owner = User.find(@bike.user_id)
    @reviews = @bike.reviews
  end

  def index_owner
    @current_user = current_user
    @bikes = policy_scope(Bike)
  end

  def new
    @new = true
    @bike = Bike.new

    authorize Bike
  end

  def create
    authorize Bike

    new_bike = Bike.new(params_permit)
    new_bike.rating = [1, 2, 3, 4, 5].sample
    new_bike.user = current_user

    new_bike.save!

    flash[:just_created] = "Created \"#{new_bike.name}\" Successfully!"

    # redirect_to my_bikes_path, just_created: "Created #{new_bike.name} successfully!"
    redirect_to my_bikes_path
  end

  def edit
    @edit = true
    authorize @bike
  end

  def update
    authorize @bike

    @bike.update(params_permit)

    flash[:just_updated] = "Updated \"#{@bike.name}\" Successfully!"

    redirect_to my_bikes_path
  end

  def destroy
    authorize @bike

    @bike.destroy

    @current_user = current_user
    @bikes = policy_scope(Bike)
    render :index_owner
  end

  private

  def set_bike
    @bike = Bike.find(params[:id])
  end

  def params_permit
    params.require(:bike).permit(:name, :category, :size, :photo, :price, :address)
  end
end

app/views/bikes/:edit.html.erb
<h1>Bikes#:edit</h1>
<p>Find me in app/views/bikes/:edit.html.erb</p>

app/views/bikes/:index.html.erb
<h1>Bikes#:index</h1>
<p>Find me in app/views/bikes/:index.html.erb</p>

app/views/bikes/:index_owner.html.erb
<h1>Bikes#:index_owner</h1>
<p>Find me in app/views/bikes/:index_owner.html.erb</p>

app/views/bikes/:new.html.erb
<h1>Bikes#:new</h1>
<p>Find me in app/views/bikes/:new.html.erb</p>

app/views/bikes/:show.html.erb
<h1>Bikes#:show</h1>
<p>Find me in app/views/bikes/:show.html.erb</p>

app/views/bikes/_form.html.erb
<%= simple_form_for @bike do |form| %>
  <%= form.input :name %>
  <%= form.input :address, id: 'bike_address' %>
  <%= form.input :category, collection: ['Mountain', 'BMX', 'Road', 'Fixi', 'Electric', 'City', 'Fatbike'] %>
  <%= form.input :price, :label => "Price per Day" %>
  <%#= form.input :description %>
  <%#= form.input :gender, collection: ['M', 'F'] %>
  <%#= form.input :size, collection: ['sm', 'md', 'lg'] %>
  <%= form.input :photo, class: "btn btn-primary" %>
  <%= form.input :photo_cache, as: :hidden %>
  <% if @new %>
    <%= form.submit "Create Bike", class: "btn btn-primary", id: "create-btn" %>
  <% elsif @edit %>
    <%= form.submit "Update Bike", class: "btn btn-primary", id: "update-btn" %>
  <% end %>
<% end %>

app/views/bikes/_infowindow.html.erb
<%= link_to bike_path(bike), class: "map-link" do %>
  <%= cl_image_tag bike.photo, class: "map-image-tag" %>
  <div class="map-img-container">
    <p class="name"><%= bike.name %></p>
    <p class="price"><%= format('%.2f', bike.price) %>$ per day</p>
    <p class="reviews">
      <% bike.rating.times do %>
        <i class="fas fa-star star-green"></i>
      <% end %>
      (<%= rand(100) %> reviews)
    </p>
  </div>
<% end %>

app/views/bikes/_search_form.html.erb
<%= form_tag bikes_path, method: :get do %>
  <!-- <div class="form-group search-form-group">
    <%= text_field_tag :query,
      params[:query],
      class: "form-control",
      placeholder: "Search for bikes"
    %>
  </div> -->

  <div class="form-group search-form-group">
    <%= label_tag 'category', 'Browse by Category' %>
    <% categories = ['All', 'Mountain', 'BMX', 'Road', 'Fixi', 'Electric', 'City', 'Fatbike'] %>
    <%= select_tag :category,
        options_for_select(categories),
        class: "form-control" %>
  </div>

  <div class="form-group search-form-group">
    <%= label_tag 'rating', 'Minimum rating' %>
    <% ratings = ['1 star', '2 stars', '3 stars', '4 stars', '5 stars'] %>
    <%= select_tag :rating,
        options_for_select(ratings),
        class: "form-control" %>
  </div>

  <div class="text-right">
    <input type="submit" value="Search" class="btn btn-primary">
  </div>
<% end %>

app/views/bikes/edit.html.erb
<h1>Update your bike "<%= @bike.name %>"</h1>

<%= render "form" %>

app/views/bikes/index.html.erb
<%# <h1>Bikes#:index</h1>
<p>Find me in app/views/bikes/:index.html.erb</p> %>

<div class="semi-banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1544361591-36e31038df92?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=750&q=80);">
  <div class="banner-info d-flex justify-content-between h-100">
    <div class="d-flex flex-column justify-content-between h-100">
      <div>
        <h2>Rent a bike whenever, wherever!</h2>
        <p>Browse through numerous types of bikes specific to your needs.</p>
      </div>
      <%= link_to "Browse on Map", bikes_map_path, class: 'btn btn-lg btn-light-blue w-50 text-white' %>
    </div>
    <%= render "search_form" %>
  </div>
</div>
<div class="container">

    <% if @message == 'category' %>
      <div class="search-message">
        <!-- We found <span class="bikes-count"><%= @bikes.count %> bikes</span> matching your search -->
        We found <span class="bikes-count"><%= pluralize @bikes.count, "bike" %></span> in category <span class="bikes-count">"<%= @category %>"</span>, with a rating of <span class="bikes-count"><%= pluralize @rating, "star" %></span> or more
      </div>
    <% elsif @message == 'all' %>
      <div class="search-message">
        <!-- We found <span class="bikes-count"><%= @bikes.count %> bikes</span> matching your search -->
        We found <span class="bikes-count"><%= pluralize @bikes.count, "bike" %></span> in all categories, with a rating of <span class="bikes-count"><%= pluralize @rating, "star" %></span> or more
      </div>
    <% end %>
    <div class="cards">
        <% if user_signed_in? %>
            <%# Do not show user's bikes %>
            <% @bikes = @bikes.reject do |bike| %>
                <% bike.user == current_user %>
            <% end %>
        <% end %>
        <% @bikes.each do |bike| %>
            <%= link_to bike_path(bike.id), class:"card_link" do %>
                <div class="card-bike">
                  <%= cl_image_tag(bike.photo) %>
                  <div class="card-bike-infos">



                    <div class="card-bike-infos">

                      <div class="d-flex justify-content-between">
                        <h2><%= bike.name %></h2>
                        <%= avatar_for(bike.user) %>
                      </div>





                      <div class="price d-flex justify-content-between mt-2">
                        <p>
                          <% bike.rating.times do %>
                            <i class="fas fa-star star-yellow"></i>
                          <% end %>
                          <% (5 - bike.rating).times do %>
                            <i class="far fa-star star-yellow"></i>
                          <% end %>
                          <%= rand(300) %>
                        </p>
                        <h6>$<%= format('%.2f', bike.price) %></h6>
                      </div>
                    </div>
                  </div>
                </div>
            <% end %>
        <% end %>
    </div>
</div>

<%#= link_to "MAP", bikes_map_path, id: 'map-button', class: 'btn btn-lg btn-maps' %>

app/views/bikes/index_map.html.erb
<h1>Browse on Map</h1>

<div
  id="map"
  style="width: 100%;
  height: 600px;"
  data-markers="<%= @markers.to_json %>"
  data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
></div>

<%= link_to "CARDS", bikes_path, id: 'map-button', class: 'btn btn-lg btn-maps' %>

app/views/bikes/index_owner.html.erb
<% if @destroy %>
  <div class="alert alert-success alert-dismissable fade show" role="alert">
    Bike successfully deleted
  </div>
<% end %>

<div class="d-flex justify-content-between align-items-center my-3 top-header">
  <h1>My Bikes</h1>

  <%= link_to "Add a new bike to rent", new_bike_path, class: "btn btn-success btn-lg" %>

</div>

<% @bikes.each do |bike| %>
  <div class="card-product my-5">
    <%= cl_image_tag bike.photo %>
    <div class="card-product-infos d-flex flex-grow-1 flex-column justify-content-between align-items-start">
      <div class="info-text flex-grow-1 d-flex justify-content-between">
        <div class="flex-grow-1">
          <div class="info-header d-flex justify-content-between align-items-center">
            <p class="bike-title"><%= bike.name %></p>
            <p class="category mt-0">
              <%= bike.category %>
            </p>
          </div>

          <div class="category-reviews d-flex justify-content-between align-items-center"">


            <p class="price-per-night"><%= format('%.2f', bike.price) %>$ per day</p>

            <p class="reviews">
              <% bike.rating.times do %>
                <i class="fas fa-star star-green"></i>
              <% end %>
              <% (5 - bike.rating).times do %>
                <i class="far fa-star star-green"></i>
              <% end %>
              (<%= rand(100) %> reviews)
            </p>
          </div>




          <!-- <p class="description"><%= bike.description %></p> -->

        </div>

      </div>

      <div class="card-buttons d-flex justify-content-between align-items-center">
        <div>
          <%= link_to "More info", bike_path(bike), class: "btn btn-primary" %>

        </div>
        <div class="buttons">
          <%= link_to edit_bike_path(bike), class: "btn btn-warning edit-btn", title: 'Edit Bike', data: { toggle: 'popover', content: 'Content',  placement: 'left', trigger: 'hover'} do %>
            <i class="fas fa-edit"></i>
          <% end %>
          <% # link_to "Delete", bike_path(bike), method: "delete", class: "btn btn-danger delete-btn" %>
          <button class="btn btn-danger delete-btn" data-toggle="popover" title="Delete Bike" data-content="Content" data-placement="right" data-trigger="hover" id="<%= bike.id %>" data-token="<%= form_authenticity_token %>">
            <i class="fas fa-trash"></i>
          </button>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/bikes/new.html.erb
<h1>Add a new bike</h1>

<%= render "form" %>

app/views/bikes/show.html.erb
<div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%=cl_image_path @bike.photo, crop: :fill %>')">
  <%= link_to bikes_path, class: "back-arrow" do %>
    <i class="fas fa-arrow-left"></i> Back
  <% end %>
  <h2 class="bike__title"><%= @bike.name %>
  <% if policy(@bike).edit? %>
    <%= link_to edit_bike_path(@bike.id), class: "edit_btn" do%>
    <i class="fas fa-pencil-alt"></i>
    <% end %>
  <% end %></h2>
</div>
<div class="bike__info--container">
  <div class="specs__wrapper">
    <div class="specssheet" >
      <h4 class="specs__title">Specs sheet</h4>
      <ul class="specs">
        <li class="spec__info"><strong>Category:</strong> <%=@bike.category %></li>
<!--         <li class="spec__info"><strong>Description:</strong> <%= @bike.description %></li>
        <li class="spec__info"><strong>Gender:</strong> <%=@bike.gender %></li>
        <li class="spec__info"><strong>Size:</strong> <%= @bike.size %></li> -->
        <li class="spec__info"><strong>Price:</strong> $<%= format('%.2f', @bike.price) %></li>
        <% counter = 0 %>
        <!-- <li class="spec__info"><strong>Rating:</strong> <% 5.times do %>
          <i class="fa <%= @bike.rating > counter ? 'fa-star' : 'fa-star-o' %>"></i>
            <% counter += 1 %>
          <% end %>
        </li> -->
        <li class="spec__info">
          <strong>Rating:</strong>
          <% @bike.rating.times do %>
            <i class="fas fa-star star-yellow"></i>
          <% end %>
          <% (5 - @bike.rating).times do %>
            <i class="far fa-star star-yellow"></i>
          <% end %>
        </li>
        <li class="spec__info"><strong>Owner:</strong>
          <% if @bike.user.avatar?  %>
            <%= link_to user_profile_path(@bike.user.id) do %>
              <%= @bike.user.first_name %>
              <%= avatar_for(@bike.user) %>
            <% end %>
          <% else %>
            <%= link_to user_profile_path(@bike.user.id), class: "owner__link" do %>
              <%= @bike.user.first_name %>
              <%= avatar_for(@bike.user) %>
            <% end %>
          <% end %>
        </li>

      </ul>
      <%= image_tag 'skidmarks.png', class: "skidmarks" %>
      <%= image_tag 'skidmarks.png', class: "skidmarks2" %>
    </div>
  </div>
  <div class="booking-form">
    <h4 class="specs__title book-me">Book me!</h4>
    <%= render "shared/booking_form", bike: @bike, booking: @booking %>
    <% if @bike.user != current_user %>
    <p class="contact"><span class="contact__title">Any questions, comments, request?</span>
      <a href="mailto:<%= @bike.user.email %>?Subject=Info%20about%20<%= @bike.name %>" target="_blank" class="mailto">Contact <%= @bike.user.first_name %></a>
    </p>
    <% end %>
  </div>
</div>

<div class="reviews-container mt-5">
  <% if @reviews.empty? %>
      <ul id="reviews-list">
        <%= render "reviews/no_reviews" %>
      </ul>
  <% else %>
    <h4 class="specs__title">What users say about this bike</h4>
    <ul id="reviews-list">
      <% @reviews.each do |review| %>
        <%= render "reviews/show_opacity1", review: review %>
      <% end %>

    </ul>
  <% end %>

  <h4 class="specs__title">Leave a Review</h4>
  <%= render "reviews/form", bike: @bike, review: Review.new %>
</div>

<h4 class="specs__title map__title mt-5">How far is it?</h4>
<div
  id="map_bike"
  style="width: 100%;
  height: 20rem;"
  data-markers="<%= @bike__markers.to_json %>"
  data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
></div>